### ISSUE TITLE
Some improvements I can think of.

### ISSUE THREAD

**Issue by biteuthusiast** [cronoh/nanovault#13]
Hi,

First of all, thanks for NanoVault. It's, in my opinion, what the average user experience should be.

Here are some points to make the software better :

1.  When importing a wallet, only the first key is loaded. A Electrum-like loading system would be better : load addresses until you find 20 unused addresses in a row. This would avoid some half a second heart attack to people loading their holding and seeing a 0 XRB balance before they understand that they have to load more accounts.
2. The wallet allow only 10 addresses. For privacy reasons, the wallet should allow more than that. To avoid server overload, maybe reduce the update rate: allow to check the balance of 10 addresses no matter how many address you use. People using 10 times more addresses are going to have a update rate divided by 10 witch is a fair trade of for their privacy.
3. For the same privacy reasons, showing the number of transaction per account on /accounts would be useful.
3. Browser POW has already been discussed in other issues.
4. When arriving to /send, the default 'from' account should not be the first one but the first with a non-zero balance.
5. Beeing able to see the global transaction history would be nice. I think it may be a valuable feature (and probably hard to implement) since, from what I saw, the official nano wallet does not even provide this.
6. Beeing able to send XRB without selecting the 'from' would be nice too. If I have an account A, B and want to send to C. The wallet would do (A->B) then (B->C) if neither A or B have enough balance. Doing (A->C) and (B->C) to send the exact amount would not be good because it gives too much information: A and B private keys are mine while only B private key is mine in the first case. From what I saw, this is not implemented in the other wallets.

I will to look to the code to see if I can help (even if I am not a web dev).

**Comment by ThunderFD** [comment]
hey, some great ideas here, but you should probably split them up into multiple github issues instead of one big one, so that the dev can work on them one by one.

1. good idea, **make a github issue about this**

2. didn't know that, also good idea, **make a github issue about this**

3. I guess this could be neat

4. -- yep

5. & 7. I would group these. nice ideas, but they _could make you accidentally send from the wrong account_

6. the node won't be able to guarantee the correct order of transactions even if keeping timestamps for them, since they might have happened in different order, but I guess it'd be a nice to have?

**Comment by cronoh** [comment]
Sorry for taking so long to reply here @biteuthusiast and thank you a ton for all of the feedback!

1. Has been implemented by @termhn and merged in - try it out and let us know how it works!
2. Ideally you can manage unlimited accounts, but the potential load it opens the servers up to at the moment, even for non-malicious users, is a little bit too big.  To properly attack this feature, the accounts page needs to show you the index of the accounts it has, and allow you to load accounts from arbitrary account indexes.  That way you could realistically be using account index 1, 50, 1000, and 5000 all at the same time (Instead of 1, 2, 3, etc).  So to really solve the problem we need more advanced control of which accounts you have in your wallet - something I absolutely plan on in the future but is out of the scope of this issue at the moment.
3. This is an interesting idea, I will play with it a bit in the future redesigns of the accounts page. Thanks!
4. Should be working good, let me know if you run into any issues.
5. This has been added in https://github.com/cronoh/nanovault/commit/b7ba4210f764435e1e478ded60107c16769fafe6 - Thanks for the suggestion!
6. Unfortunately this is not easily doable since none of the blocks themselves have any time related information.  The only way to really do it is to have a central server tracking the timestamps of transactions, and you trust it to be accurate.  It's an interesting idea for the future, but out of scope for now I would say.
7. I think in this scenario the same amount of information is exposed pretty much, anyone interested only has to look one block deeper.  It would be an interesting feature to do split payments though, from either end, sending from many of your accounts to one recipient, or sending from one of your accounts to many recipients.  Something to look into in the future for sure.

Thanks again for all of the feedback - I'm going to mark this issue as closed, but feel free to open a new issue with any other changes.
