### ISSUE TITLE
Default localStorage to off and provide strong warning when turning it on

### ISSUE THREAD

**Issue by termhn** [cronoh/nanovault#16]
Storing data unencrypted in localStorage is a pretty massive vulnerability--a single XSS attack could steal anything stored there. See: https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Local_Storage

Therefore I propose we should 

1. Really consider turning off the localStorage option by default (or providing a warning/option while creating the account) and
2. Definitely enforce locking the wallet before it is saved to localStorage

**Comment by cronoh** [comment]
I think going with #2 by default is the best way to go here.  Essentially, only save the wallet unencrypted if the 'Do not lock on close' option is selected, otherwise encrypt it on save (If its not already locked, for example when adding a new account).  I think the wallet loses a lot of its reusability for basic users if we don't save by default, but I agree that there is no good reason not to always encrypt that info unless the user specifically sets it to not to.

There are a few considerations I will need to think through to make sure all of the situations are covered, but I will try and get this implemented soon and update here when it's ready.  Thanks for the feedback @termhn!

**Comment by cronoh** [comment]
Because the wallet already automatically locks (And therefore encrypts) on close, I am going to consider that a sufficient solution for now.  Please reply if you think this needs to be changed!
