### ISSUE TITLE
App version (and auto-update?)

### ISSUE THREAD

**Issue by HostFat** [cronoh/nanovault#24]
After reading about your last release
https://github.com/cronoh/nanovault/releases/tag/v1.0.2

I tried to run again the app, to see how the auto-update works.

Maybe it worked, maybe not.

I didn't get any message, and I don't know where I can check its version from the interface.

**Comment by cronoh** [comment]
@HostFat The notifications around the process could still use some improvement for sure.  How it works is:
- When you launch the application, it checks GitHub for any new releases.  If it finds one, it starts downloading it in the background.  
- Once the download is finished, it should send a system notification that lets you know a new update has been downloaded and will be applied when you close the app.
- The next time you open the app, it should be fully updated.

You cant really check the current version of the application right now except for on OSX.  I will try and get a fix in there so you can tell which version you are on.  You pretty much always have the latest version of the application though if you restart it (Since it will always check for the latest version and download it when you start the app)
