### ISSUE TITLE
Add alias support

### ISSUE THREAD

**Issue by stefonarch** [cronoh/nanovault#26]
https://documenter.getpostman.com/view/2206404/nano-alias/RVfsFYHj#1a0df0fa-4cc8-3ded-eec5-58ee80628e77

It's built on suggestion from Zack , work in progress.

**Comment by cronoh** [comment]
Hey @stefonarch, thanks for the suggestion.

I'm going to be waiting on an official stance from the Nano core team on aliases before I decide which direction to take.  Since there are already two competing alias services (Nanode, Canoe) I think it would be very limiting to NanoVault to implement either of them before there is official word.  I'm going to mark this issue as closed for now, but feel free to continue adding any opinions in, and know that aliases are definitely something I am planning to add in when its safe and smart for the users.

**Comment by stefonarch** [comment]
As I learned Tyler has implemented this on suggestion/delegated from core team, there should be a check for existing aliases in nanode already in place. But sure it'cutting edge stuff and has bugs and missing features, recovery and so on.
