### ISSUE TITLE
Representative set improvement

### ISSUE THREAD

**Issue by hobbysome** [cronoh/nanovault#32]
Add option to set a default rep for every new account
Add option to change all previous account's rep

**Comment by ThunderFD** [comment]
sounds like a nice idea

**Comment by cronoh** [comment]
@hobbysome I like the idea!  Since the current representative settings work 'OK', I am going to put it slightly on the back-burner and mark it as a future enhancement. It will fit well into the incoming improvements to the representative UI though, which I hope will help make decentralizing easier than ever before.  Thanks for the feedback!

**Comment by hobbysome** [comment]
@cronoh seems good to me )
