### ISSUE TITLE
Pending transaction issue 

### ISSUE THREAD

**Issue by Lightyears27** [cronoh/nanovault#60]
HI, 
I tried so solve the problem by reading solved issues but was not possible.
I tried to move NANO from Binance to Nanovault almost 7 hours ago.
Tried to withdrawal 1 NANO, 0,99 NANO included fee but it's stucked.
I made access with Ledger Nano S, confirmed address, Proof of Work pop up appeared but it's loading forever.
Tried to set Auto-receive on and off...nothing.
Any suggestion?
Thank you very much

**Comment by fallerOfFalls** [comment]
I just had this problem (I think?)

It kept saying that the ledger app wasn't loaded. It turned out it's because I had the Ledger Live app open as well. When I closed Ledger Live (I also unplugged it and plugged it back in to make sure it would do the automatic receive thing) it gave me the green "Ledger Ready" indicator and signed the receive transaction :)

**Comment by cronoh** [comment]
I believe this was related to an issue the work server was having at the moment.  Please update/reply if you are experiencing any other issues. Sorry for the problems!
