### ISSUE TITLE
Nanovault connecting to Ledger issue

### ISSUE THREAD

**Issue by thesonofja** [cronoh/nanovault#61]
I'm totally confused about how to login with my ledger on Nanovault desktop Windows wallet.

I noticed that when I open the wallet it does not ask for a password at all. So, someone could just click on it and see my balances and possibly even send or receive coins without my permission ( as long as a password isn't required to send a receive unless I set that up upon installation but I did not write that down anywhere and have no record of it) and I'm concerned about that. 

There is no button at all that indicates to connect with a ledger. And yes I have it downloaded on my ledger to the latest version.  So it seems I'm not actually using my ledger to connect.

Also a quick question that has been bothering me for some time in regards to this wallet and with my other wallets for other cryptos as well...

And in general I just wonder about the security of using a Ledger to access 3rd party wallets. Is there a possibility that I'm exposing my ledger keys or compromising the Ledger in any way when I log in using it? I have certainly been hearing (as long as I understand this correctly) that this is a possibility in which case it's not 100% secure.

I always want to be 100% sure that it's TOTALLY secure to log in using my Ledger with 3rd party wallets.

Any advice and instructions are greatly appreciated

Regards,

Jason

**Comment by cronoh** [comment]
Hey @thesonofja,

Are you using version 1.0.4 (Stable release) of the desktop wallet?  Right now, ledger support for desktop is only in the alpha version which I do not recommend using unless you are working with me directly to test it.  That said, the desktop version with ledger functions identically to the web version.  

It does not require a password on your wallet because every transaction needs to be confirmed on your Ledger device, which requires your Ledger PIN to use.  Anyone using your computer could indeed see your accounts and balances if they looked, but they would be unable to send or receive anything.

To connect with your ledger, I recommend following this guide here: http://blog.nanovault.io/guides/use-your-ledger-device-with-nanovault/ and only with the web version for now.

As for the security of it - your Ledger device protects your private keys/seed and never exposes them to any application that is interfacing with the it.  This means that even if the website had malicious code in it, it could never get the seed or private keys from your Ledger.  The one possible attack against a Ledger, is to have a malicious wallet send bad data to it.  So as long as you always look on your ledger device and make sure the destination/amount is correct, you are always safe.

Hopefully that helps, let me know if you have other questions!

**Comment by thesonofja** [comment]
Cronoh thank you for your reply. Yes I am using that version. I locked it so to unlock it I need to enter the password which I did. I want to make sure what you are saying about a transaction needing to be confirmed on my Ledger device is the case here. Im pretty sure it was set up with a Ledger but I also remember having issue with that originally so want to double check.

How can I test this without sending? Will it send automatically without needing confirmation on the Ledger if the wallet was set up differently? I just want to make sure it can be tested without sending anything...

Thanks...

Jason

**Comment by thesonofja** [comment]
Actually I just reread your first reply and I understand you dont recommend using the desktop version with Ledger and its in the beginning stages. This confirms I did NOT set it up with Ledger then. So, my question would be is it less secure to use the desktop vs the web version with Ledger?

Would it just ask for my password when sending/receiving funds on the desktop vs. confirming on Ledger? Why would this be more secure than a Ledger on the web version?

Regards,

Jason

**Comment by cronoh** [comment]
When using a Ledger device, the web version is just as safe as the desktop version.  As mentioned above, your Ledger never shows the private key or seed, no matter if its via web or desktop.  When sending or receiving with a Ledger device, it never requires a password - it does require you to confirm the transaction on your Ledger though, which requires you to unlock it with the PIN.

So to be clear - you can have your ledger wallet loaded loaded into nanovault, and then disconnect your device - you can still see your accounts and balances, but it is impossible to sign a new transaction until you connect your ledger, unlock it, and then also confirm the transaction on the Ledger.

**Comment by aramsdale** [comment]
Hey @cronoh! 

It appears that nanovault isn't seeing my ledger today... tacking onto this ticket versus creating a new one. Can you inspect?

**Comment by thesonofja** [comment]
Cronoh I know it's been a while but I finally am getting around to this now. I connected my ledger pretty easily with the Nano app on the web version and sent funds from the desktop wallet to the web wallet without any issues. I simply just deleted the desktop version from my computer because I didn't see anywhere where I could delete the wallet. Is that the best route?

And just want to confirm that if I lose my ledger the only security in getting web wallet back up and running is to use the 24 word seed that comes with the Ledger to get Ledger account back?

Thank you...

Jason
