### ISSUE TITLE
problems on all sides ...

### ISSUE THREAD

**Issue by dooonos** [cronoh/nanovault#83]
how can it be that I try to send some nanos ... and confirming with the nano s ledger ... it does not get to perform operation ... it does not matter chrome that brave .. that nothing .. then I get under vault d desktop ... and there if i receive nano ... but then i try to send and can not paste the address ... and i can not send them ,,, buff please i like technology ,,, but ?????

**Comment by schonthal** [comment]
I sent via ledger my nano from Binance to my nanovault two weeks ago. It still says pending deposit and my account balance is zero. Please help .

**Comment by Eothred** [comment]
@schonthal See #74 I think you probably have the same issue. No worries, your funds aren't lost, there just seem to be some sort of unresolved hiccup when it stops running receive requests. For me an immediate fix was to delete all wallet data and import again. Since you are using a Ledger there should be no harm in doing so.

@dooonos I struggle a bit to understand exactly what/which issues you have. One sounds like the issue with browser, and there is a known issue that the web version cannot be used to receive transactions anymore, Google decided to break the Ledger support. I am not aware of any other browsers that properly support the Ledger. The desktop version is recommended for the time being I believe. Please provide more clarity about what exact issues you have, the steps needed to reproduce your error (according to your best understanding of what you did), and what system you are using, version of NanoVault etc to aid @cronoh in assisting.

Disclaimer: I am not a NanoVault developer, just providing my 5 cents.

**Comment by cronoh** [comment]
Thank you for the assistance @Eothred.

Are you still experiencing any issues @schonthal?  If so please reply here with a detailed description of your latest issue and I will try and help.

**Comment by schonthal** [comment]
Hi,

I cannot import my existing wallet using my Ledger nano x. For some reason, it says my “Ledger not connected ...” even though it is connected and I am in the Nano app. 

Help would be appreciated.
