### ISSUE TITLE
Add spacing in FIAT value display

### ISSUE THREAD

**Issue by stefonarch** [cronoh/nanovault#9]
![schermata-25-09-24-34](https://user-images.githubusercontent.com/10681413/36639479-e43db788-1a0d-11e8-9fc5-5ac4b7fcfca8.png)

For some currencies it's hard to read.

**Comment by cronoh** [comment]
Okay I agree @stefonarch - Let me see what I can do, it is using the Angular currency pipe for the most part, so I suspect its only with certain currencies that we would want to add the space.  I'll look into a solution and let you know when I've got an update.  Thanks for the feedback!

**Comment by cronoh** [comment]
@stefonarch I added in a change so that it uses the currency symbol instead of the currency name for most currencies in https://github.com/cronoh/nanovault/commit/802b78689f9229e5066ff3a6cd084a54af5ca275, which should make the fiat displays look better for most currencies.  Let me know if this doesn't solve the issue for you!
